"""add user statistics

Revision ID: 0a86712b6a81
Revises: bf25e7940d23
Create Date: 2026-10-03 18:53:40.135404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a86712b6a81'
down_revision: Union[str, Sequence[str], None] = 'bf25e7940d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_urls_created', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('total_clicks', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_clicks')
        batch_op.drop_column('total_urls_created')

    # ### end Alembic commands ###
